export const TOUR_STEPS = [
  {
    id: 'draft-mode',
    target: 'draft-badge',
    title: 'Draft mode',
    description: "You're working in a draft. Changes are saved automatically, and won't go live until you publish.",
    dialogSide: 'bottom',
    spotlightPadding: 8,
    borderRadius: 999,
  },
  {
    id: 'tab-structure',
    target: 'tab-structure',
    title: 'Default & Channel values',
    description: 'Use the Default and Channel value tabs to fill in default information and channel specific information',
    dialogSide: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'variant-selector',
    target: 'variant-selector',
    title: 'Select variant + language',
    description: 'Select the product variant and language combination to adjust the specific product information.',
    dialogSide: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'attribute-badges',
    target: 'attribute-badge',
    title: 'How attributes work',
    description: 'Badges on each field show whether it can vary by variant (V), channel (C), or language (L).',
    dialogSide: 'left',
    spotlightPadding: 8,
    borderRadius: 100,
  },
  {
    id: 'publish-button',
    target: 'publish-button',
    title: 'Publish',
    description: "Publishing a variant to catalog means saving it within the catalog but not publishing it live to the website. It's a setting that lets you create a product.",
    dialogSide: 'bottom',
    spotlightPadding: 8,
  },
]
